// This file is automatically generated by the export-package plugin. Do not edit it manually.
export const MajorVersion = 0;
export const MinorVersion = 17;
export const PatchVersion = 2;
export const VersionNumber = `${MajorVersion}.${MinorVersion}.${PatchVersion}`;
